plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kozhedub.atlantic4145'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kozhedub.atlantic4145'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
